# Project Name
TARGET = chorus

DEBUG = 1
OPT = -Og

# Sources
CPP_SOURCES = chorus.cpp

# Library Locations
LIBDAISY_DIR = /Users/benmj/Desktop/CS12-FinalProject-BMJ/libDaisy
DAISYSP_DIR = /Users/benmj/Desktop/CS12-FinalProject-BMJ/DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
